train: true
seed: 22
model_name_or_path: ./model/facebook/bart-large  # facebook/bart-large
natural_label: False  # whether to use the natural label
early_stopping_patience: 4  # early stopping patience

defaults:
  - _self_
  - dataset: conll2003
  - training_args: baseline